# Generated by Django 2.0.3 on 2021-04-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFurnitureShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
