# Generated by Django 2.0.3 on 2021-04-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineFurnitureShop', '0002_carddetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='price',
        ),
        migrations.AddField(
            model_name='carddetail',
            name='cardholdername',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='cvvnumber',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='expmonth',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carddetail',
            name='expyear',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
